server:
  port: 9080
  servlet:
    context-path: /canciones

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://ec2-174-129-255-37.compute-1.amazonaws.com:5432/db2bvrqufvjn2q
    username: rjoxbyfkuejqxw
    password: 55d24463950c7d686c65af88c155d87a54770152dafe7ef8738e80319211141b
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    ##show-sql: true

logging:
  level:
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN